name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget
        wget -q https://services.gradle.org/distributions/gradle-6.7-all.zip
        unzip gradle-6.7-all.zip
        sudo mv gradle-6.7 /opt/gradle
        sudo ln -s /opt/gradle/bin/gradle /usr/local/bin/gradle

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: android-build
        path: app/build/outputs/
